
auth.token=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

defaults.org=other-wvk
defaults.project=react-native

defaults.url=https://sentry.io/
