import { ExpenseCategory } from '../types/expense';

interface WeightedKeyword {
  term: string;
  weight: number;
}

const categoryKeywords: Record<ExpenseCategory, WeightedKeyword[]> = {
  Comida: [
    // General food terms
    { term: 'restaurante', weight: 8 },
    { term: 'taqueria', weight: 9 },
    { term: 'cafe', weight: 6 },
    { term: 'cafeteria', weight: 7 },
    { term: 'comida', weight: 7 },
    { term: 'alimentos', weight: 7 },
    { term: 'cocina', weight: 5 },
    { term: 'pizza', weight: 8 },
    { term: 'hamburguesa', weight: 8 },
    { term: 'tacos', weight: 9 },
    { term: 'torta', weight: 6 },
    { term: 'sushi', weight: 8 },
    { term: 'panaderia', weight: 8 },
    { term: 'carniceria', weight: 7 },
    { term: 'fruteria', weight: 7 },
    { term: 'verduleria', weight: 7 },
    { term: 'tortilleria', weight: 8 },
    { term: 'pasteleria', weight: 7 },
    // Delivery
    { term: 'uber eats', weight: 9 },
    { term: 'didi food', weight: 9 },
    { term: 'rappi', weight: 8 },
    // Brands
    { term: 'oxxo', weight: 7 },
    { term: 'starbucks', weight: 8 },
    { term: 'mcdonalds', weight: 9 },
    { term: 'burger king', weight: 9 },
    { term: 'subway', weight: 8 },
    { term: 'dominos', weight: 8 },
    { term: 'little caesars', weight: 8 },
    { term: 'kfc', weight: 8 },
    { term: 'pollo loco', weight: 8 },
    { term: 'church', weight: 5 },
    { term: 'carl', weight: 4 },
    { term: 'vips', weight: 8 },
    { term: 'sanborns', weight: 7 },
    { term: 'italiannis', weight: 8 },
    { term: 'chilis', weight: 8 },
    { term: 'applebees', weight: 8 },
    { term: 'toks', weight: 8 },
    { term: 'la casa de tono', weight: 9 },
    { term: 'el fogon', weight: 7 },
    { term: 'el portón', weight: 7 },
    // Supermarkets
    { term: 'walmart', weight: 6 },
    { term: 'soriana', weight: 6 },
    { term: 'chedraui', weight: 6 },
    { term: 'heb', weight: 6 },
    { term: 'la comer', weight: 6 },
    { term: 'city market', weight: 6 },
    { term: 'superama', weight: 6 },
    { term: 'super', weight: 4 },
    { term: 'bodega aurrera', weight: 6 },
    { term: 'costco', weight: 5 },
    { term: 'sams club', weight: 5 },
    { term: "sam's", weight: 5 },
    // Convenience
    { term: '7-eleven', weight: 5 },
    { term: 'seven eleven', weight: 5 },
    { term: 'circle k', weight: 5 },
    { term: 'extra', weight: 3 },
    // Local Mexican food
    { term: 'birrieria', weight: 9 },
    { term: 'birria', weight: 8 },
    { term: 'carnitas', weight: 9 },
    { term: 'pozoleria', weight: 9 },
    { term: 'pozole', weight: 8 },
    { term: 'antojitos', weight: 8 },
    { term: 'loncheria', weight: 8 },
    { term: 'fonda', weight: 7 },
    { term: 'cocina economica', weight: 8 },
    { term: 'comedor', weight: 7 },
    { term: 'mariscos', weight: 8 },
    { term: 'marisqueria', weight: 9 },
    { term: 'cevicheria', weight: 9 },
    { term: 'tostadas', weight: 7 },
    { term: 'gorditas', weight: 7 },
    { term: 'tlayuda', weight: 8 },
    { term: 'tamales', weight: 7 },
    { term: 'barbacoa', weight: 8 },
    { term: 'menudo', weight: 7 },
    { term: 'tortas', weight: 6 },
    { term: 'jugos', weight: 6 },
    { term: 'agua fresca', weight: 6 },
    { term: 'nieve', weight: 6 },
    { term: 'paleteria', weight: 7 },
    { term: 'heladeria', weight: 7 },
    // More brands
    { term: 'el portón', weight: 7 },
    { term: 'punta del cielo', weight: 8 },
    { term: 'cielito querido', weight: 8 },
    { term: 'el pendulo', weight: 7 },
    { term: 'sushi itto', weight: 8 },
    { term: 'bisquets', weight: 7 },
    { term: 'wings army', weight: 8 },
    { term: 'hooters', weight: 7 },
    { term: 'mercado roma', weight: 6 },
    // Más marcas y conceptos
    { term: 'pollo feliz', weight: 8 }, { term: 'el pollo feliz', weight: 9 },
    { term: 'burger inn', weight: 8 }, { term: 'tortas frontera', weight: 8 },
    { term: 'el tizoncito', weight: 8 }, { term: 'super tacos', weight: 8 },
    { term: 'jugos california', weight: 7 }, { term: 'smoothie', weight: 6 },
    { term: 'burritos', weight: 7 }, { term: 'enchiladas', weight: 8 },
    { term: 'quesadillas', weight: 7 }, { term: 'elotes', weight: 7 },
    { term: 'esquites', weight: 7 }, { term: 'cafe combate', weight: 7 },
    { term: 'la preferida', weight: 6 }, { term: 'marinela', weight: 6 },
    { term: 'bimbo', weight: 6 }, { term: 'snack', weight: 5 },
    { term: 'botanas', weight: 6 }, { term: 'frituras', weight: 6 },
    { term: 'sabritas', weight: 7 }, { term: 'barcel', weight: 7 },
    { term: 'panificadora', weight: 7 }, { term: 'deli', weight: 5 },
    { term: 'agua mineral', weight: 5 }, { term: 'jarritos', weight: 6 },
    { term: 'big cola', weight: 5 }, { term: 'heineken', weight: 5 },
    { term: 'corona', weight: 4 }, { term: 'modelo', weight: 4 },
    { term: 'tecate', weight: 4 }, { term: 'pacifico', weight: 4 },
    { term: 'abarrotes', weight: 7 }, { term: 'miscelanea', weight: 6 },
    { term: 'tiendita', weight: 5 }, { term: 'colonia', weight: 3 },
  ],
  Transporte: [
    // Ride-hailing
    { term: 'uber', weight: 8 },
    { term: 'didi', weight: 8 },
    { term: 'cabify', weight: 8 },
    { term: 'beat', weight: 7 },
    { term: 'indriver', weight: 8 },
    { term: 'taxi', weight: 8 },
    // Gas
    { term: 'gasolina', weight: 9 },
    { term: 'pemex', weight: 9 },
    { term: 'mobil', weight: 7 },
    { term: 'shell', weight: 7 },
    { term: 'bp', weight: 6 },
    { term: 'gulf', weight: 6 },
    { term: 'oxxo gas', weight: 8 },
    { term: 'combustible', weight: 8 },
    { term: 'diesel', weight: 7 },
    { term: 'magna', weight: 8 },
    { term: 'premium', weight: 5 },
    // Public transit
    { term: 'metro', weight: 7 },
    { term: 'metrobus', weight: 8 },
    { term: 'autobus', weight: 8 },
    { term: 'camion', weight: 5 },
    { term: 'ruta', weight: 4 },
    // Tolls & parking
    { term: 'caseta', weight: 9 },
    { term: 'peaje', weight: 9 },
    { term: 'estacionamiento', weight: 8 },
    { term: 'parking', weight: 7 },
    // Bus companies
    { term: 'ado', weight: 8 },
    { term: 'primera plus', weight: 8 },
    { term: 'etn', weight: 8 },
    { term: 'estrella blanca', weight: 8 },
    { term: 'estrella roja', weight: 8 },
    { term: 'pullman', weight: 7 },
    { term: 'flecha amarilla', weight: 8 },
    // Airlines
    { term: 'volaris', weight: 9 },
    { term: 'aeromexico', weight: 9 },
    { term: 'vivaaerobus', weight: 9 },
    { term: 'viva aerobus', weight: 9 },
    { term: 'vuelo', weight: 6 },
    { term: 'avion', weight: 6 },
    { term: 'aeropuerto', weight: 5 },
    // Vehicle
    { term: 'verificacion', weight: 7 },
    { term: 'mecanico', weight: 7 },
    { term: 'taller', weight: 5 },
    { term: 'llantera', weight: 7 },
    { term: 'autozone', weight: 7 },
    { term: 'refaccion', weight: 6 },
    { term: 'grua', weight: 8 },
    { term: 'valet', weight: 6 },
    { term: 'auxilio vial', weight: 8 },
    { term: 'seguro auto', weight: 7 },
    { term: 'tenencia', weight: 8 },
    { term: 'placas', weight: 7 },
    { term: 'licencia conducir', weight: 7 },
    { term: 'moto', weight: 5 },
    { term: 'bicicleta', weight: 4 },
    { term: 'scooter', weight: 5 },
    { term: 'autopista', weight: 7 },
    { term: 'cuota', weight: 5 },
    { term: 'litros magna', weight: 9 },
    { term: 'litros premium', weight: 9 },
    { term: 'litros diesel', weight: 9 },
    { term: 'tag', weight: 6 }, { term: 'televia', weight: 8 },
    { term: 'iave', weight: 8 }, { term: 'pase express', weight: 8 },
    { term: 'tag iave', weight: 9 }, { term: 'recarga bip', weight: 8 },
    { term: 'renta de auto', weight: 8 }, { term: 'nacional', weight: 5 },
    { term: 'alamo', weight: 7 }, { term: 'hertz', weight: 7 },
    { term: 'europcar', weight: 7 }, { term: 'pago vialidad', weight: 8 },
    { term: 'revision vehicular', weight: 7 }, { term: 'cita vehicular', weight: 7 },
    { term: 'hidrosina', weight: 9 }, { term: 'petro 7', weight: 9 },
    { term: 'g500', weight: 7 }, { term: 'bioil', weight: 7 },
  ],
  Entretenimiento: [
    // Cinema
    { term: 'cine', weight: 8 },
    { term: 'cinepolis', weight: 9 },
    { term: 'cinemex', weight: 9 },
    // Streaming
    { term: 'netflix', weight: 9 },
    { term: 'spotify', weight: 9 },
    { term: 'disney', weight: 8 },
    { term: 'hbo', weight: 8 },
    { term: 'amazon prime', weight: 8 },
    { term: 'apple tv', weight: 8 },
    { term: 'youtube premium', weight: 8 },
    // Gaming
    { term: 'steam', weight: 8 },
    { term: 'xbox', weight: 8 },
    { term: 'playstation', weight: 8 },
    { term: 'nintendo', weight: 8 },
    { term: 'videojuego', weight: 8 },
    // Events
    { term: 'ticketmaster', weight: 9 },
    { term: 'superboletos', weight: 8 },
    { term: 'concierto', weight: 8 },
    { term: 'teatro', weight: 8 },
    { term: 'museo', weight: 7 },
    { term: 'espectaculo', weight: 7 },
    { term: 'evento', weight: 5 },
    { term: 'parque', weight: 5 },
    { term: 'six flags', weight: 9 },
    { term: 'la feria', weight: 7 },
    // Nightlife
    { term: 'bar', weight: 7 },
    { term: 'antro', weight: 8 },
    { term: 'club', weight: 5 },
    { term: 'cerveza', weight: 5 },
    { term: 'bebida', weight: 4 },
    // Sports
    { term: 'gimnasio', weight: 7 },
    { term: 'sport city', weight: 8 },
    { term: 'smart fit', weight: 8 },
    { term: 'deportivo', weight: 6 },
    { term: 'estadio', weight: 7 },
    { term: 'boliche', weight: 8 },
    { term: 'bowling', weight: 8 },
    { term: 'karting', weight: 8 },
    { term: 'laser tag', weight: 8 },
    { term: 'escape room', weight: 8 },
    { term: 'trampolín', weight: 7 },
    { term: 'kidzania', weight: 8 },
    { term: 'zoologico', weight: 7 },
    { term: 'acuario', weight: 7 },
    { term: 'mundo e', weight: 7 },
    { term: 'terraza', weight: 5 },
    { term: 'salon corona', weight: 7 },
    { term: 'cerveceria de barrio', weight: 8 },
    { term: 'tequila', weight: 5 },
    { term: 'mezcal', weight: 5 },
    { term: 'copa', weight: 4 },
    { term: 'mixup', weight: 7 },
    { term: 'musica', weight: 4 },
    { term: 'apple music', weight: 8 },
    { term: 'tidal', weight: 7 },
    { term: 'crunchyroll', weight: 8 },
    { term: 'paramount', weight: 7 },
    { term: 'palacio de los deportes', weight: 9 },
    { term: 'arena ciudad de mexico', weight: 9 },
    { term: 'foro sol', weight: 9 }, { term: 'autocinema', weight: 8 },
    { term: 'fun planet', weight: 8 }, { term: 'topgolf', weight: 8 },
    { term: 'strike', weight: 7 }, { term: 'bowlero', weight: 8 },
    { term: 'twitch', weight: 7 }, { term: 'patreon', weight: 7 },
  ],
  Salud: [
    // Pharmacies
    { term: 'farmacia', weight: 9 },
    { term: 'farmacia guadalajara', weight: 10 },
    { term: 'farmacias del ahorro', weight: 10 },
    { term: 'farmacias similares', weight: 10 },
    { term: 'similares', weight: 8 },
    { term: 'farmacia san pablo', weight: 10 },
    { term: 'benavides', weight: 8 },
    // Medical
    { term: 'doctor', weight: 9 },
    { term: 'medico', weight: 9 },
    { term: 'hospital', weight: 9 },
    { term: 'clinica', weight: 9 },
    { term: 'consultorio', weight: 8 },
    { term: 'consulta', weight: 7 },
    { term: 'salud digna', weight: 10 },
    { term: 'chopo', weight: 9 },
    { term: 'laboratorio', weight: 8 },
    { term: 'analisis', weight: 6 },
    { term: 'estudio', weight: 4 },
    // Dental
    { term: 'dentista', weight: 9 },
    { term: 'dental', weight: 8 },
    { term: 'odontologia', weight: 9 },
    // Vision
    { term: 'optica', weight: 8 },
    { term: 'lentes', weight: 7 },
    { term: 'oculista', weight: 9 },
    { term: 'oftalmologo', weight: 9 },
    // Misc
    { term: 'medicamento', weight: 8 },
    { term: 'medicina', weight: 7 },
    { term: 'receta', weight: 6 },
    { term: 'tratamiento', weight: 6 },
    { term: 'terapia', weight: 7 },
    { term: 'fisioterapia', weight: 8 },
    { term: 'psicologia', weight: 8 },
    { term: 'nutricion', weight: 7 },
    { term: 'seguro medico', weight: 8 },
    { term: 'imss', weight: 8 },
    { term: 'issste', weight: 8 },
    { term: 'vitaminas', weight: 7 },
    { term: 'suplemento', weight: 7 },
    { term: 'proteina', weight: 6 },
    { term: 'gnc', weight: 7 },
    { term: 'nutrisa', weight: 7 },
    { term: 'enfermera', weight: 6 },
    { term: 'cirugia', weight: 8 },
    { term: 'urgencias', weight: 8 },
    { term: 'ambulancia', weight: 8 },
    { term: 'rayos x', weight: 8 },
    { term: 'ultrasonido', weight: 8 },
    { term: 'resonancia', weight: 8 },
    { term: 'tomografia', weight: 8 },
    { term: 'vacuna', weight: 7 },
    { term: 'salud digna', weight: 10 },
    { term: 'laboratorios chopo', weight: 9 },
    { term: 'hospital angeles', weight: 9 },
    { term: 'star medica', weight: 9 },
    { term: 'clinica dental', weight: 9 },
    { term: 'ortodoncia', weight: 8 },
    { term: 'corona dental', weight: 8 },
    { term: 'extraccion dental', weight: 8 },
    { term: 'medica sur', weight: 9 }, { term: 'medica abc', weight: 9 },
    { term: 'centro medico', weight: 8 }, { term: 'cruz roja', weight: 8 },
    { term: 'paramedico', weight: 8 }, { term: 'masaje', weight: 6 },
    { term: 'spa', weight: 5 }, { term: 'acupuntura', weight: 7 },
    { term: 'suero', weight: 7 }, { term: 'jeringa', weight: 6 },
    { term: 'pañales', weight: 7 }, { term: 'pediatria', weight: 8 },
    { term: 'lentes de contacto', weight: 8 },
    { term: 'salud digna', weight: 10 }, { term: 'chopo', weight: 9 },
  ],
  Educacion: [
    // Schools
    { term: 'escuela', weight: 8 },
    { term: 'universidad', weight: 9 },
    { term: 'colegiatura', weight: 10 },
    { term: 'inscripcion', weight: 7 },
    { term: 'matricula', weight: 8 },
    { term: 'instituto', weight: 7 },
    { term: 'colegio', weight: 7 },
    { term: 'preparatoria', weight: 8 },
    { term: 'secundaria', weight: 7 },
    { term: 'primaria', weight: 7 },
    { term: 'kinder', weight: 7 },
    // Online
    { term: 'curso', weight: 7 },
    { term: 'udemy', weight: 9 },
    { term: 'platzi', weight: 9 },
    { term: 'coursera', weight: 9 },
    { term: 'domestika', weight: 8 },
    { term: 'crehana', weight: 8 },
    { term: 'codecademy', weight: 8 },
    { term: 'capacitacion', weight: 7 },
    { term: 'certificacion', weight: 7 },
    // Materials
    { term: 'libros', weight: 6 },
    { term: 'libreria', weight: 6 },
    { term: 'gandhi', weight: 7 },
    { term: 'papeleria', weight: 6 },
    { term: 'material escolar', weight: 8 },
    { term: 'utiles', weight: 6 },
    { term: 'tesis', weight: 8 },
    // Language
    { term: 'idioma', weight: 7 },
    { term: 'ingles', weight: 5 },
    { term: 'duolingo', weight: 8 },
    { term: 'clase', weight: 5 },
    { term: 'tutorial', weight: 5 },
    { term: 'seminario', weight: 7 },
    { term: 'taller', weight: 4 },
    { term: 'diplomado', weight: 8 },
    { term: 'maestria', weight: 9 },
    { term: 'doctorado', weight: 9 },
    { term: 'especialidad', weight: 8 },
    { term: 'posgrado', weight: 8 },
    { term: 'examen', weight: 5 },
    { term: 'examen extraordinario', weight: 7 },
    { term: 'reinscripcion', weight: 8 },
    { term: 'servicio escolar', weight: 7 },
    { term: 'credencial escolar', weight: 7 },
    { term: 'tecnologico', weight: 6 },
    { term: 'tec de monterrey', weight: 9 },
    { term: 'unam', weight: 8 },
    { term: 'ibero', weight: 8 },
    { term: 'anáhuac', weight: 8 },
    { term: 'anahuac', weight: 8 },
    { term: 'uia', weight: 7 },
    { term: 'office depot', weight: 6 },
    { term: 'officemax', weight: 6 },
    { term: 'papeleria', weight: 7 },
    { term: 'cuaderno', weight: 6 },
    { term: 'lapiz', weight: 5 },
    { term: 'pluma', weight: 4 },
    { term: 'mochila', weight: 5 },
    { term: 'calculadora', weight: 6 },
    { term: 'aws', weight: 7 }, { term: 'google cloud', weight: 7 },
    { term: 'azure', weight: 7 }, { term: 'comptia', weight: 8 },
    { term: 'microsoft learn', weight: 7 }, { term: 'libreria el sotano', weight: 8 },
    { term: 'fondo de cultura', weight: 8 }, { term: 'material didactico', weight: 8 },
    { term: 'guarderia', weight: 9 }, { term: 'estancia infantil', weight: 9 },
    { term: 'libro de texto', weight: 8 }, { term: 'texto universitario', weight: 8 },
  ],
  Otros: [],
};

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

export function classifyExpense(text: string): ExpenseCategory {
  const normalized = normalize(text);
  const scores: Record<string, number> = {};

  for (const [category, keywords] of Object.entries(categoryKeywords) as [
    ExpenseCategory,
    WeightedKeyword[],
  ][]) {
    if (keywords.length === 0) continue;
    let total = 0;
    for (const { term, weight } of keywords) {
      if (normalized.includes(normalize(term))) {
        total += weight;
      }
    }
    if (total > 0) {
      scores[category] = total;
    }
  }

  if (Object.keys(scores).length === 0) {
    return 'Otros';
  }

  return Object.entries(scores).reduce(
    (best, [cat, score]) => (score > best[1] ? [cat, score] : best),
    ['Otros', 0],
  )[0] as ExpenseCategory;
}
